
services:
  mysql:
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: eduai-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  ai-service:
    build: ./ai-service
    container_name: eduai-ai-service
    volumes:
      - ./ai-service:/app
  

    env_file:
      - ./ai-service/.env
    ports:
      - "8000:8000"

  auth-service:
    build: ./auth-service
    command: sh -c "sleep 5 && npm run seeds && npm start"
    container_name: eduai-auth-service
    volumes:
      - ./auth-service:/app
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./auth-service/.env
    ports:
      - "4000:4000"

  gateway-api:
    build: ./gateway-api
    command: sh -c "npm run migrate && sleep 5 &&npm start"
    container_name: eduai-gateway
    volumes:
      - ./gateway-api:/app
    depends_on:
      ai-service:
        condition: service_started
      mysql:
        condition: service_healthy
      auth-service:
        condition: service_started
    env_file:
      - ./gateway-api/.env
    ports:
      - "3000:3000"
